### ISSUE TITLE
Adoption of MILESTONES

### ISSUE THREAD

**Issue by 42piratas** [MARKETProtocol/community#24]
* Although it's really tricky to define milestones/deadlines in a scenario in which most collaborators are ocasional/part-time collaborators, <IF> in the future we'll have to attend any kind of business deadline expectation, I'd say we should start experimenting alternatives as soon as possible, so we see what happens in practice and have the time to adjust accordingly. 
* Assuming that's the case, we could, as an introduction/experiment with Milestones, instead of defining specific milestones/sprints/etc, we could simply use the Engineering Weekly meetings as references, therefore each Milestone being a calendar week number, and issues assigned to a certain milestone should be complete by the respective meeting time.
* If that's something we don't need to worry for now, please close @pelsasser

**Comment by pelsasser** [comment]
@42piratas - one of my goals is for creating greater clarity for contributors to the bigger picture, and I think milestones assist in that process.

I am less concerned with dates of deadlines for the moment until we bring on more full time staff, because it is near impossible to accomplish with the community sourced development process.

**Comment by 42piratas** [comment]
@pelsasser In that case, I think using calendar weeks might not be a good approach, and, instead, we should clarify what the milestones are in the first place (e.g. Alpha, beta 1 - or any other reference). 

I've seen that you have a card in the project board backlog to create a Roadmap. That for sure would be a great way (maybe the best one) to define the milestones.

**Comment by 42piratas** [comment]
@pelsasser Do you mean those cards you create directly on the board instead of regualar issues? 

If so, that's why I added to tomorrow's meeting agenda the item _"Suggestion: use the project board backlog for product-related backlog, and any suggestion/tasks related to processes/tools/etc should become issues in community"_. 

Those cards are not helpful at all, even because there's no way of commenting them, and that's why I'd suggest using only issues - if related to the product(s), create issues inside the respective repo; if general tasks/goals (process, tools, etc), create issues in the community repo.

**Comment by rojosnow** [comment]
Due to the growth of the team, this issue is in progress again. Work is underway to organize the product and development planning process using GitHub and one of the popular overlays (ZenHub).

We will be experimenting for two weekly iterations to see if ZenHub is going to work for the team
