### ISSUE TITLE
Expectations on the core team as a contributor

### ISSUE THREAD

**Issue by 0xean** [MARKETProtocol/community#33]
We have created expectations for contributors in regards to bounties / style / commits, etc.

We should be held responsible the other way as well, and clearly outline what they can expect from "MARKET Protocol Core"

This is an open discussion but some things that come to mind are 

- 1 business day or less response to PR's, comment on issues
- 1 business day or less pay out of all merged work for bounties
- Good faith effort to clearly portray the scope of work in issues, and if some parts are unclear, to draw attention to that potential issue and a possible solution

would love more feedback here @eswarasai @pchuck @42piratas @cryptomental @perfectmak @rojosnow

**Comment by 42piratas** [comment]
@pelsasser I'd appreciate more details in our Engineering Weekly tomorrow
