### ISSUE TITLE
Create a repo to provide high level vision plus business needs of API layer

### ISSUE THREAD

**Issue by 42piratas** [MARKETProtocol/community#37]
from @pelsasser 

MARKET.js Library

Create repo and provide high level vision plus business needs of API layer. 

https://0xproject.com/docs/0xjs is a great starting place.  Essentially many of our partners are already using this typescript API to allow them to create their decentralized exchanges.  They are expecting something similar from us to enable very low barriers to entry.

**Comment by pelsasser** [comment]
https://github.com/MARKETProtocol/MARKET.js
