### ISSUE TITLE
Update Templates of new issues

### ISSUE THREAD

**Issue by 42piratas** [MARKETProtocol/community#38]
Move the section "Before you start work" to the top

**Comment by 42piratas** [comment]
@pelsasser the `ISSUE_TEMPLATE.md` replicates across the different repos, somehow similar to a submodule?

**Comment by pelsasser** [comment]
It doesn't currently, that would be nice if we could create that however. 

perhaps the main copy lives in `community`?

cc @pchuck

**Comment by 42piratas** [comment]
@pelsasser In fact, one of the reasons we deactivated `meta` was because with submodules we can't replicate only specifics, you need to replicate the entire repo --- so, in theory, there's no way to replicate only the issues template using submodules.

I asked, though, because I had the impression they were being replicated somehow, and I couldn't figure out how.

**Comment by 42piratas** [comment]
Done!
