### ISSUE TITLE
Internal Engineering Call 2018-06-11

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/community#57]

**Comment by eswarasai** [comment]
Review PRs
- https://github.com/MARKETProtocol/dApp/pull/189
- https://github.com/MARKETProtocol/dApp/pull/190
- https://github.com/MARKETProtocol/website/pull/138

**Comment by pelsasser** [comment]
@rojosnow create issues for 
- collateral in market.js
- bot in market api
