### ISSUE TITLE
Integrate new, safer signing techniques for orders.

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/community#77]
Signing of non human readable data (as in an orderHash) is unsafe and has been abused.  Eventually meta mask will phase this out, and we need to implement new functionality for signing orders.

See the following articles 
- https://consensys.zendesk.com/hc/en-us/articles/360004427792
- https://medium.com/metamask/scaling-web3-with-signtypeddata-91d6efc8b290

**Comment by rojosnow** [comment]
Issue moved to [MARKETProtocol/dApp #464](https://github.com/MARKETProtocol/dApp/issues/464) via [**ZenHub**](https://www.zenhub.com/)
