### ISSUE TITLE
Backlog of ideas to improve GitHub PM

### ISSUE THREAD

**Issue by 42piratas** [MARKETProtocol/community#8]
**LABELS could be _additionaly_ used for**
~- Indication of priority level on all issues;~
~- Label `waiting review`;~
~- If there are_ any repos containing issues that require different skill sets (e.g. Solidy, design, etc), indicate the respective language/technology of each issue with labels to facilitate search/filtering;~   

~**Adoption of MILESTONES**~
~- Although it's tricky to define milestones for all issues due to occasional/part-time collaborators, we could start using labels at least for those issues we are sure we can commit to (e.g. full-time staff).~  
~- As an introduction/experiment with Milestones, instead of defining new milestones, we could simply use the Engineering Weekly meetings as references, therefore each Milestone being a calendar week number, and issues assigned to a certain milestone should be complete by the meeting time.~

**Root project BOARD**
- Add column `In Review` to the board, to make more clear the distinction between issues that are being tackled by engineers and tickets awaiting review.
- Issues should be automatically ordered by priority in the columns

**Comment by pelsasser** [comment]
@42piratas is there an easy way your familiar with to standardize the labels across all the repos? that would be very nice.  Colors and text prefferably.

**Comment by 42piratas** [comment]
@pelsasser There's no native way, but I found this [open source tool](https://github.com/repo-utils/org-labels) that apparently would do the trick. Check the command `standardize`.

**Comment by pelsasser** [comment]
@42piratas is your suggestion to also make this the location for the "high level" vision that would allow contributors to understand what we are building and where we are headed?  I want to make sure to address that feedback, since I think it makes a ton of sense and will help everyone.

**Comment by 42piratas** [comment]
@pelsasser TBH, at this point I'm not sure if using a single issue will be the easiest way anymore. Maybe one issue per suggestion would work better. What do you think?

**Comment by 42piratas** [comment]
@pelsasser Btw: I will document that in the README as well.

**Comment by pelsasser** [comment]
> @pelsasser TBH, at this point I'm not sure if using a single issue will be the easiest way anymore. Maybe one issue per suggestion would work better. What do you think?

works for me
