### ISSUE TITLE
Add description of PM board columns to documentation

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/community#9]
> i think it is useful for everyone to understand not only what automations are applied as changes are made to issues/pr's, but also what the four columns mean. here is a list of the currently applied automations and the current working definition of each column
> todo
>   definition: planned but not started
>   automation: all newly added or reopened issues and pull requests
> 
> in progress
>   definition: actively being worked on
>   automation: none (the act of (explicitly/manually) moving a card here indicates that a particular person has initiated work on an item)
> 
> done
>   definition: work that is completed (and thoroughly tested)
>   automation: all closed issues and all merged pull requests. also, all closed but not merged pull requests
> 
> backlog
>   definition: work hasn't yet been decomposed into issues, has issues or ambiguities that prevent it from being moved to 'todo' or isn't yet high enough priority to be moved to 'todo'
>   automation: none

**Comment by pchuck** [comment]
https://github.com/MARKETProtocol/community/commit/5250fb540d00fbdd6b19ecf09e030060910b0c38
